### ISSUE TITLE
Plugin does not work on submodules

### ISSUE THREAD

**Issue by iamandrewluca** [jamesward/play-auto-refresh#40]
I have a project composed of 3 submodules
```
root
    persistance
    test
    web
```
I added plugin in `root/project/plugins.sbt`
When I `~run` in `root` plugin is starting, but I don't have any routes in `root`, main project is in `web`.  
How can I activate plugin for `web` module?  
I tried to add it with `addPlugin` to `web` module as `BrowserNotifierPlugin` but no change.  
How it should be added on submodule?  
Reload server is starting only when `~run` on `root`.  
Is there any way I can start it on submodule?  
Thanks!

**Comment by jamesward** [comment]
Does it work if you do: `sbt ~web/run` ?

**Comment by iamandrewluca** [comment]
@jamesward unfortunately no
```
[info] Done updating.
[info] 
[info] --- (Running the application, auto-reloading is enabled) ---
[info] 
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[info] 
[info] (Server started, use Ctrl+D to stop and go back to the console...)
[info] 
[info] Stopping Play fork run ...
[info] p.c.s.NettyServer - Stopping server...

[info] JVM exiting, shutting down Play fork run ...
[info] Play fork run already stopped ...
[info] Forked Play process exited with status: 0
[success] Total time: 171 s, completed Jan 26, 2017 6:27:45 PM
1. Waiting for source changes... (press enter to interrupt)
```

I had to use `sbt "~web/run"`, without quotes is saying
```
zsh: no such user or named directory: web
```

**Comment by jamesward** [comment]
Maybe:
```
lazy val web = (project in file("modules/web")).enablePlugins(PlayScala, SbtWeb, BrowserNotifierPlugin)
  .dependsOn(persistence, testkit % Test)
```

**Comment by iamandrewluca** [comment]
@jamesward same. Only when I `sbt "~run"`
```
[info] Compiling 59 Scala sources and 1 Java source to /home/andreiluca/Projects/myproject/modules/web/target/scala-2.11/classes...

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[info] Started auto-refresh WebSocket on port 9001

(Server started, use Ctrl+D to stop and go back to the console...)

Created new window in existing browser session.
[info] Formatting 4 Scala sources {...}web(compile) ...
```
```
[info] Compiling 4 Scala sources and 1 Java source to /home/andreiluca/Projects/myproject/modules/web/target/scala-2.11/classes...
[error] application - 

! @72of7le9g - Internal server error, for (GET) [/] ->
```

**Comment by jamesward** [comment]
Oh, I think you need to remove Play's plugin from the `root` project:
```
lazy val root = (project in file(".")).aggregate(persistence, web, testkit).dependsOn(persistence, web, testkit)
```

And then try: `sbt "~web/run"`

**Comment by iamandrewluca** [comment]
@jamesward does not work
```
[info] Done updating.
[error] scala.pickling.PicklingException: Not a primitive: scala.Nothing, found JNothing
[error]         at sbt.serialization.json.VerifyingJSONPickleReader.sbt$serialization$json$VerifyingJSONPickleReader$$unpickleHelper$1(JSONPickleFormat.scala:367)

...

[error] Play fork run has failed due to:
[error] scala.pickling.PicklingException: error in unpickle of primitive unpickler 'java.lang.Integer':
[error] tag in unpickle: 'scala.Nothing'
[error] message:
[error] Not a primitive: scala.Nothing, found JNothing
[error]         at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:31)
```

**Comment by jamesward** [comment]
Hmm...  I'm not sure on that one.  I haven't used the Scala Pickling stuff.

**Comment by iamandrewluca** [comment]
@jamesward Ok, thanks for feedback! I will close the issue for now.
Have a great weekend!

**Comment by jamesward** [comment]
So I wasn't more helpful!
